chore: Assimilate git-config action

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -36,13 +36,37 @@ jobs:
         with:
           tool: cargo-semver-checks@0.34
 
-      - name: Configure git user from GitHub token
-        uses: MarcoIeni/git-config@v0.1
-        with:
-          GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}
-    
       - name: Run release-plz
         run: |
+          export GITHUB_TOKEN=GH_TOKEN
+          
+          if [ -z "${GITHUB_TOKEN+x}" ]; then
+            echo "Error: environment variable GITHUB_TOKEN is undefined"
+            exit 1
+          fi
+
+          if [ -z "$GITHUB_TOKEN" ]; then
+            echo "Error: environment variable GITHUB_TOKEN is empty"
+            exit 1
+          fi
+
+          # The environment variable GITHUB_TOKEN is read by the `gh` cli
+          VIEWER_JSON=$(gh api graphql -f query='query { viewer { name login databaseId }}' --jq '.data.viewer')
+          VIEWER_NAME=$(jq --raw-output '.name | values' <<< "${VIEWER_JSON}")
+          VIEWER_LOGIN=$(jq --raw-output '.login' <<< "${VIEWER_JSON}")
+          VIEWER_DATABASE_ID=$(jq --raw-output '.databaseId' <<< "${VIEWER_JSON}")
+
+          # Set the variable USER_NAME to the value of VIEWER_NAME if VIEWER_NAME is set and not null.
+          # Otherwise, set USER_NAME to the value of VIEWER_LOGIN.
+          USER_NAME="${VIEWER_NAME:-${VIEWER_LOGIN}}"
+          USER_EMAIL="${VIEWER_DATABASE_ID}+${VIEWER_LOGIN}@users.noreply.github.com"
+
+          git config --global user.name "${USER_NAME}"
+          git config --global user.email "${USER_EMAIL}"
+
+          echo "name=${USER_NAME}" >> "${GITHUB_OUTPUT}"
+          echo "email=${USER_EMAIL}" >> "${GITHUB_OUTPUT}"
+
           echo "-- Running release-plz release-pr --"
           release_pr_output=$(release-plz release-pr\
               --git-token ${GH_TOKEN}\
